/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class JFAppSwing extends javax.swing.JFrame {

    /**
     * Creates new form JFAppSwing
     */
    public JFAppSwing() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBboton = new javax.swing.JButton();
        jLmensaje = new javax.swing.JLabel();
        jTFCampoDeTexto = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMacciones = new javax.swing.JMenu();
        jMIsaludar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIinicializar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi primer panel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jBboton.setText("Saludar");
        jBboton.setToolTipText("pincha para decir hola");
        jBboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludarActionPerformed(evt);
            }
        });

        jLmensaje.setText("Hola!");

        jTFCampoDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCampoDeTextoActionPerformed(evt);
            }
        });

        jMacciones.setText("Acciones");

        jMIsaludar.setText("Saludar");
        jMIsaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludarActionPerformed(evt);
            }
        });
        jMacciones.add(jMIsaludar);
        jMacciones.add(jSeparator1);

        jMIinicializar.setText("Inicializar");
        jMIinicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIinicializarActionPerformed(evt);
            }
        });
        jMacciones.add(jMIinicializar);

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMacciones.add(jMenuItem1);

        jMenuBar1.add(jMacciones);

        jMayuda.setText("Ayuda");
        jMayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMayudaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLmensaje)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBboton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFCampoDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBboton)
                    .addComponent(jTFCampoDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLmensaje)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saludarActionPerformed
        // TODO add your handling code here:
        jLmensaje.setVisible(true);
        jLmensaje.setText("Hola " + jTFCampoDeTexto.getText()+ ".Bienvenido a la aplicación Swing");
    }//GEN-LAST:event_saludarActionPerformed

    private void jTFCampoDeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCampoDeTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCampoDeTextoActionPerformed

    private void jMIinicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIinicializarActionPerformed
        // TODO add your handling code here:
        inicializar();
        
    }//GEN-LAST:event_jMIinicializarActionPerformed

    private void jMayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMayudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Hecho en España", "Información útil", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMayudaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       // jdNuevoUsuario nuevo = new jdNuevoUsuario(rootPane, true);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAppSwing().setVisible(true);
            }
        });
    }
    
    public void inicializar(){
        jLmensaje.setVisible(false);
        jTFCampoDeTexto.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBboton;
    private javax.swing.JLabel jLmensaje;
    private javax.swing.JMenuItem jMIinicializar;
    private javax.swing.JMenuItem jMIsaludar;
    private javax.swing.JMenu jMacciones;
    private javax.swing.JMenu jMayuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTFCampoDeTexto;
    // End of variables declaration//GEN-END:variables
}
